
export enum USERNAME_VALIDATOR {
    MIN_LENGTH = 4,
    MAX_LENGTH = 20,
}

export enum PASSWORD_VALIDATOR  {
    MIN_LENGTH = 8,
    MAX_LENGTH = 20,
}

export enum USER_ERRORS {
    USERNAME_ALREADY_EXISTS = '23505'
}
