version: '3'

services:
  cockpit:
    container_name: cockpit
    build:
      context: ./src/packages/cockpit
    volumes:
      - ./src/packages/cockpit:/etc/nginx/
    ports:
      - 8080:8080
    networks:
      - monorepo_network
  auth_api:
    container_name: auth_api
    build:
      context: ./
      dockerfile: ./Dockerfile.AuthAPI
    volumes:
      - ./auth/:/usr/src/app/
    networks:
      - monorepo_network
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
  marvel_api:
    container_name: marvel_api
    build:
      context: ./
      dockerfile: ./Dockerfile.Marvel
    volumes:
      - ./marvel/:/usr/src/app/
    networks:
      - monorepo_network
    ports:
      - 3001:3001
      - 9230:9229
    command: npm run start:debug
networks:
  monorepo_network:
    driver: bridge
