name: Building DC

on:
  push:
    branches: [ main ]
    paths:
      - 'src/packages/dc/**'
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.DC  --tag monorepo_dc:$(date +%s)
