name: Building Marvel

on:
  push:
    branches: [ main ]
    paths:
      - 'src/packages/marvel/**'
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.Marvel  --tag monorepo_marvel:$(date +%s)
