name: Building Marvel

on:
  push:
    branches: [ main ]
    paths:
      - 'marvel/**'
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./marvel/Dockerfile  --tag monorepo-marvel:$(date +%s)
