name: Building Auth API

on:
  push:
    branches: [ main ]
    paths:
      - 'auth/**'
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.AuthAPI  --tag monorepo_marvel:$(date +%s)
